### ISSUE TITLE
Empresas com S/A - Erro ao salvar .rds

### ISSUE THREAD

**Issue by lsdelmondes** [msperlin/GetFREData#1]
Professor, boa tarde.

Está dando erro para empresas que possuem S/A no nome, em vez de S.A., acredito que o R confunde a barra / como se fosse um novo diretório.

PBG
`Error in saveRDS(x, con) : não é possível abrir a conexão
Além disso: Warning message:
In saveRDS(x, con) :
  não foi possível abrir o arquivo 'gfred_cache/fre_parsed_cache_files/fre_cache_cvm13773_PBG S/A_2019_id93882_ver7.rds': No such file or directory`

Vulcabras
`Error in saveRDS(x, con) : não é possível abrir a conexão
Além disso: Warning message:
In saveRDS(x, con) :
  não foi possível abrir o arquivo 'gfred_cache/fre_parsed_cache_files/fre_cache_cvm11762_VULCABRAS/_2019_id92269_ver5.rds': No such file or directory`

**Comment by msperlin** [comment]
Obrigado. Vou arrumar. 

At,

**Comment by msperlin** [comment]
Quando eu arrumar, fecho o issue.

**Comment by msperlin** [comment]
Arrumado em nova versão.
