### ISSUE TITLE
Zip baixado vazio

### ISSUE THREAD

**Issue by lsdelmondes** [msperlin/GetFREData#7]
Professor, espero que esteja bem.

Estou com o seguinte erro:

> > l_fre <- get_fre_data(companies_cvm_codes = 19615,
> +                       fre_to_read = 'last',
> +                       first_year = 2020,
> +                       last_year = 2020, 
> +                       cache_folder = tempdir())
> Fetching ftp contents
> 	* Reading fre_cia_aberta_2020.zip | no cache found, reading zip file
>                                                                                                                       
> Found 1 FRE docs to read
> 
> Starting Downloads:
> -> Company 19615 | fre file 103471 (ver 11) | 2020-01-01Error in `purrr::map()`:
> ℹ In index: 1.
> ℹ With name: 1.
> Caused by error in `read_single_fre_zip_file()`:
> ! Zipped file contains 0 files. This is likelly a problem with the downloaded file. Try running the code again as the corrupted zip file was deleted and will be downloaded again.
> 
> If the problem persists, my suggestions is to remove the time period with problem.
> Run `rlang::last_trace()` to see where the error occurred.
> Warning message:
> In utils::unzip(my_zip_file, exdir = rnd_folder_name, junkpaths = TRUE) :
>   error 1 in extracting from zip file`

Para qualquer período e empresa que eu tento baixar, o resultado é que o zip não contem arquivos.

O senhor sabe como arrumar?

Obrigado!

**Comment by msperlin** [comment]
Oi @lsdelmondes . 
Rodei o código aqui e funcionou. 

![image](https://github.com/msperlin/GetFREData/assets/10583352/00411b3b-4938-4df6-8b0b-7f435a801e56)


As vez o servidor da b3 dá problema. Tenta de novo, após a limpeza da pasta de cacheamento, e deve funcionar.
